### PR TITLE
Port the shared GDoc to this website.

### PR DESCRIPTION
**Pull request by SolalPirelli**
[link to said gdoc](https://docs.google.com/document/d/13FindMBbndzZ0MXa4lNwbTjxTLKiWvslUlqwwvVU2YI/edit?usp=sharing)

Add checklists for badge criteria, and help for authors and evaluators.

I also added a section about the basics of Docker to the authors help.

As part of this, I removed the redirects to the old SOSP2019 website, and added a custom 404 page to ensure anyone following those links doesn't have a terrible experience... I could revert this and instead put the new pages in a subfolder, if keeping these old links alive is considered important.

### CODE REVIEW

**Comment by vahldiek** [comment]
Hi, Thank you for contributing this information. 

1) Specific Information
I think we should leave information that is fairly specific like the badges or Docker commands out. It is not clear if future conferences will always include all three badges or the Docker interface changes. This would result in requiring us to maintain this information. Is there a subset of this PR that is more or less timeless?
2) Who are the authors?
It would be great to include the authors of for this PR. 

I'm not sure what the rest thinks about this PR, I'll ping them...

**Comment by mrigger** [comment]
I think that the suggestions and ideas are very valuable (thanks a lot for organizing and writing this down!). I think that being more specific is a great idea in general and this would likely improve the quality of many artifacts. I also totally agree with, for example, requiring a long-term hosting platform for the "Available" badge. 

Nevertheless, I feel a bit conflicted, since imposing some of these rules might result in artifacts being left out. Like papers, there is a wide variety of artifacts and the guidelines might not be applicable to all of them (e.g., think of datasets or [proof artifacts](https://proofartifacts.github.io/guidelines/)).

I'm also wondering if specifying badge criteria is useful here since the publisher and/or the AE chairs have the final say. For example, EuroSys is sponsored by ACM, which has [its own badging rules](https://www.acm.org/publications/policies/artifact-review-and-badging-current), which conflict with those in this PR. For example, for the ACM "Available" badge, no README is necessary:
> Artifacts do not need to have been formally evaluated in order for an article to receive this badge. In addition, they need not be complete in the sense described above. They simply need to be relevant to the study and add value beyond the text in the article. Such artifacts could be something as simple as the data from which the figures are drawn, or as complex as a complete software system under study.

Perhaps one possible way to proceed with this would reach out to a publisher (perhaps Usenix, which has no standardized badging system) and discuss this with them?

**Comment by vahldiek** [comment]
@mrigger I believe NISO has started standardizing badges: https://www.niso.org/publications/rp-31-2021-badging Their definitions are vague enough for ACM and IEEE badges to fit into their criteria. As you said, USENIX has left this mostly to the AE chairs to determine the exact wording, but it was heavily influenced by ACM and a like.

**Comment by SolalPirelli** [comment]
Indeed these badge criteria are stricter than existing ones, which is an issue...
How about rephrasing it to say these checklists are _sufficient_ to get badges, but authors may deviate as long as they justify such deviations?
That is, most authors can just follow the steps and know they'll get their badge as long as everything works, but the authors who want to follow the less strict (and less well-defined) ACM/Usenix/... criteria can do so if they choose.

Thus, the common case will be easy for both authors and evaluators, and the uncommon/complex case is made explicit by the authors justifying why they're not doing the simple thing.
This would fix the current issue where artifact authors and evaluators have to make a decision on what is badge-worthy for every single paper, which is time-consuming and leads to inconsistencies.

In general, for both the checklists and the Docker tips, IMHO centralizing this information is important to allow every author and evaluator to benefit from it, rather than being yet another random webpage that people must find via the right google keywords (i.e., a "hidden curriculum" of sorts).

> It would be great to include the authors of for this PR.

I can make a list of everyone who contributed to the discussion. Where should such a list be on the website?

**Comment by mrigger** [comment]
> How about rephrasing it to say these checklists are _sufficient_ to get badges, but authors may deviate as long as they justify such deviations?

We can state this on this website, but the question is what relevance this has in practice. Reviewers and/or the AE chairs might decide otherwise (although the rules are probably strict enough to make that case unlikely). 

> That is, most authors can just follow the steps and know they'll get their badge as long as everything works, but the authors who want to follow the less strict (and less well-defined) ACM/Usenix/... criteria can do so if they choose.
> 
> Thus, the common case will be easy for both authors and evaluators, and the uncommon/complex case is made explicit by the authors justifying why they're not doing the simple thing.

That's the conundrum. On the one hand, with how things are currently phrased, a number of artifacts are left out. On the other hand, if we weaken these rules, they become vague like for the other badging systems. A way to address this might be to specify to what kind of artifacts this applies. Another idea would be to specify a general checklist, similar to https://www.sigplan.org/Resources/EmpiricalEvaluation/.

In general, I believe this is a great idea, so I hope I don't sound discouraging!

**Comment by SolalPirelli** [comment]
> We can state this on this website, but the question is what relevance this has in practice. Reviewers and/or the AE chairs might decide otherwise (although the rules are probably strict enough to make that case unlikely).

Right, the goal would be to convince future AE chairs to accept this, if they work for a few AEs then they can become a habit.

AE chairs can then handle the decisions on exceptions to the checklists themselves, since there should be few (and the checklists can be updated when/if some exceptions become too common), instead of requiring AE members (i.e., PhD students) to make difficult choices for every artifact.

> Another idea would be to specify a general checklist, similar to https://www.sigplan.org/Resources/EmpiricalEvaluation/.

That's a good idea indeed, once the rules become more or less formalized we could turn them into a nice cheatsheet like that.

**Comment by SolalPirelli** [comment]
Ping :smile:

I was in the SOSP'21 AEC, and the need for a proper checklist is still very much there. Some authors did not know exactly what was expected of them, and ended up wasting time for both themselves and the evaluators due to misunderstandings (e.g., making parts of the artifacts private because they didn't realize everything had to be public). Most of the time spent by evaluators was not on auditing the artifacts but on trying to get them to run, which is unfortunate.

I've created a few scripts that show how to retrofit an artifact to Docker instead of requiring complex manual steps on a bunch of cloud VMs: https://github.com/SolalPirelli/docker-artifact-eval (no license for now; perhaps this repo could be moved into this org if it's judged useful enough, and the community could contribute)

Regarding the issue of how to give advice that doesn't become dated as new versions of Docker and such are released, or as new tools supersede old ones, I think we could version basically every non-conference page in the repo, including the one with the checklists. That way, a conference artifacts website can link to e.g. v1 of the checklist and of the help pages, and these links remain valid forever; once a v2 is released, the v1 versions can have a "this is old, check out v2" banner added at the top.

I think scripts and help for authors must go hand-in-hand with checklists; authors will be understandably annoyed if they are asked to make their artifacts entirely automatable but given no official help.

**Comment by SolalPirelli** [comment]
I don't remember why I did those SOSP changes, anyway they weren't needed so I reverted them. Sorry. I also added the names of everyone (I think?) who contributed to the initial discussion, as per the first comment here.

Re: criteria listed here vs publisher criteria, short of convincing ACM+USENIX+IEEE to all use the same criteria, I think the only reasonable way to do it is to give AE chairs a predefined checklist like the one here as a basis, and let them decide when to allow exceptions (or even to copy/paste a modified version of the checklist in their call for artifacts). The criteria on this website are stricter than abstract ones like ACM's, so authors would have the choice of (1) following the checklist or (2) arguing to the chairs why they should be granted an exception (such as submitting a video for artifacts that use proprietary benchmarks). Most authors and most evaluators would then follow the checklist leading to consistent decisions, and allowing exceptional cases would be handled by the chairs and thus also lead to consistent decisions.

Re: the SIGPLAN checklist, as far as I can tell it's intended more for the PC than the AEC, since it deals with whether an evaluation is good enough. It'd be great to have some equivalent for SIGOPS and friends, but this seems orthogonal, since the AEC currently works under the assumption that papers are correct (and thus have a "good enough" eval).

**Comment by SolalPirelli** [comment]
Closing for #40, which is the implementation of this for EuroSys'22, we'll see how it goes :D

**Pull request closed without merging**
